### ISSUE TITLE
Feature count mismatch

### ISSUE THREAD

**Issue by dlimanov** [danielbohannon/Revoke-Obfuscation#11]
> Measure-RvoObfuscation /Users/user/Desktop/bad.ps1                                                                                            
Measure-Vector : Feature count mismatch (0 -ne 4998)
At /Users/user/Downloads/Revoke-Obfuscation-master/Revoke-Obfuscation.psm1:370 char:89
+ ... asurement = Measure-Vector -FeatureVector $scriptFeatures -Deep:$Deep ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Measure-Vector

not sure what to do with this one here..

**Comment by bw-0** [comment]
@dlimanov did you provide the -path or -literalpath parameter Measure-RvoObfuscation? Maybe provide a copy of the .ps1 you were trying to measure.
