### ISSUE TITLE
-NoNewLine flag on Set-Content isn't v3 compatible

### ISSUE THREAD

**Issue by mjnbrn** [danielbohannon/Revoke-Obfuscation#3]
Getting errors on Powershell 3 related to Set-Content -NoNewLine.

https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Set-Content?view=powershell-3.0

**Comment by danielbohannon** [comment]
Can you please provide the exact error that you're seeing and provide any additional context?

**Comment by mjnbrn** [comment]
Trying to run one of the examples.

205> $obfResults = Get-Content -Path .\Demo\DBOdemo*.ps1 -Raw | Measure-RvoObfuscation -Verbose -OutputToDisk
[1 of 2] OBFUSCATED     :: (88E009F26F0C960ADEF8930AC3E2997FB4E20B9206BA817FA0E9F9B16481A74A)
Set-Content : A parameter cannot be found that matches parameter name 'NoNewline'.
At C:\Users\user\opt\Revoke-Obfuscation\Revoke-Obfuscation\Revoke-Obfuscation.psm1:394 char:77
+                         Set-Content -Path $resultFile -Value $scriptContent -NoN ...
+                                                                             ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetContentCommand

[2 of 2] OBFUSCATED     :: (37FC5015C2412E34F6FD29D3F63070CD812087D308FDEC4993D363E6CD86536E)
Set-Content : A parameter cannot be found that matches parameter name 'NoNewline'.
At C:\Users\user\opt\Revoke-Obfuscation\Revoke-Obfuscation\Revoke-Obfuscation.psm1:394 char:77
+                         Set-Content -Path $resultFile -Value $scriptContent -NoN ...
+                                                                             ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetContentCommand

**Comment by danielbohannon** [comment]
Hmm, and you get 3.0 or later as your major build version when you run:

**$PSVersionTable.PSVersion**

**Comment by mjnbrn** [comment]
Correct. 
```
208> $PSVersionTable.PSVersion


Major         : 4
Minor         : 0
Build         : -1
Revision      : -1
MajorRevision : -1
MinorRevision : -1
```

**Comment by danielbohannon** [comment]
I'm not sure what could be causing this. If you pop open a separate PowerShell prompt then can you run this:

**Set-Content -Value "testing" -Path ./scTest.txt -NoNewLine**

**Comment by mjnbrn** [comment]
Tried it in a new prompt, and tried it in a -NoProfile prompt.  It doesn't like the -NoNewLine param.

```
PS C:\> set-content -value "testing" -Path .\sctest.txt -nonewline
Set-Content : A parameter cannot be found that matches parameter name 'nonewline'.
At line:1 char:49
+ set-content -value "testing" -Path .\sctest.txt -nonewline
+                                                 ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetContentCommand
```

**Comment by danielbohannon** [comment]
That's really odd. Well, at least it doesn't seem like it's an issue in Revoke-Obfuscation at least 📄  

I've not seen that before, though. At the end of the day that -NoNewLine is important if you're dropping the -OutputToDisk results into the \Whitelist\Scripts_To_Whitelist directory since that implicit newline will change the md5 read of the actual script run vs the read in hash of the output result from Revoke-Obfuscation.

**Comment by mjnbrn** [comment]
I think you might be able to use [io.file]::WriteAllText, since it doesn't appear to put in a newline, if you want to support versions of Powershell that don't like the -NoNewLine parameter.

'''
[io.file]::WriteAllText($resultFile,$Scriptcontent)

'''

Just made this change in my local psm1 file and it worked.

**Comment by mjnbrn** [comment]
If you'd like, I can submit a pull request with this change.

**Comment by danielbohannon** [comment]
After chatting with Lee it seems that there are some AST changes in PS 5.0 that may require this to be a PS5.0 project instead of PS3.0. Will figure out if that's the case and will then update the .psd1 to make PS5.0 requirement. So even if you changed that line above then the AST parsing may not occur as expected for certain classes.

**Comment by mjnbrn** [comment]
Gotcha.  I was just testing in a VM, so it's not a big deal for me.  Imagine most people will be using v5 anyway. Guess this is good to close now. Thanks!

**Comment by kincki** [comment]
hi all,

i was having the same problem with POSH v.5.1. You can use TrimEnd() function to trim out the trailing new line, as you would with -NoNewLine option in POSH v.6.0
