### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by kurtfalde** [danielbohannon/Revoke-Obfuscation#4]
Not sure this can be fixed or not but basically any script that has a signature block gets flagged as obfuscated. 

Also have a high number of short one line type things that are triggered as obfuscated basically mostly looks like things someone typed at the command line ex. "$test.Content" is a script that was triggered as being obfuscated.  Maybe a switch or something to say if the script is less than X amount of characters long then ignore?

**Comment by danielbohannon** [comment]
Realize this is a late response, but when you imported the module did you import Revoke-Obfuscation.psd1 or Revoke-Obfuscation.psm1? If you are not installing directly from PowerShell Gallery then you will want to run **Import-Module .\Revoke-Obfuscation.psd1** to properly load all required C# components used for proper feature extraction.
