### ISSUE TITLE
Missing Convert-PowerShellCommandLine.ps1 (called in Measure-RvoObfuscation - Revoke-Obfuscation.psm1, line 330)

### ISSUE THREAD

**Issue by amirubin87** [danielbohannon/Revoke-Obfuscation#7]
When calling 'Measure-RvoObfuscation' with '-CommandLine' switch, 'Convert-PowerShellCommandLine.ps1' is called ( see 'Revoke-Obfuscation.psm1', line 330), however, it does not exist.

The full line is:
'$scriptContent = . $scriptDir\Requirements\CommandLine\Convert-PowerShellCommandLine.ps1 $scriptContent'

However, '\Requirements\CommandLine\' contains only:
'ConvertToPowerShellExpression' (.cs, .exe, .ps1)

**Comment by bw-0** [comment]
@amirubin87 
fixed with https://github.com/danielbohannon/Revoke-Obfuscation/commit/38116a497e94d3973af10f7a8ed029766bf5d3d3
